import { NextRequest, NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx'

export const runtime = 'nodejs'

export async function GET(req: NextRequest) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const runId = searchParams.get('runId')
  const projectId = searchParams.get('projectId')
  if (!runId || !projectId) return NextResponse.json({ error: 'Missing params' }, { status: 400 })

  const service = createServiceClient()
  const { data: project } = await service.from('projects').select('*').eq('id', projectId).single()
  const { data: run } = await service.from('runs').select('*').eq('id', runId).single()
  const { data: answers } = await service
    .from('answers')
    .select('*, questions(question_text, order_index)')
    .eq('run_id', runId)

  const sorted = (answers ?? []).sort(
    (a: any, b: any) => (a.questions?.order_index ?? 0) - (b.questions?.order_index ?? 0)
  )

  const children: Paragraph[] = [
    new Paragraph({
      text: project?.name ?? 'Questionnaire',
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: `Generated by AnswerFlow AI · ${new Date().toLocaleDateString()}`,
        color: '888888', size: 18
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      text: 'Coverage Summary',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `Total: ${run?.total_questions ?? sorted.length}   ` }),
        new TextRun({ text: `Answered: ${run?.answered_count ?? 0}`, color: '16a34a' }),
        new TextRun({ text: `   Not Found: ${run?.not_found_count ?? 0}`, color: 'dc2626' }),
      ],
      spacing: { after: 400 },
    }),
  ]

  sorted.forEach((answer: any, idx: number) => {
    const displayAnswer = answer.edited_answer || answer.generated_answer
    const citations: string[] = answer.citations ?? []
    const isNotFound = answer.not_found
    const confidence = answer.confidence ?? 0

    children.push(
      new Paragraph({
        children: [new TextRun({
          text: `Q${idx + 1}. ${answer.questions?.question_text ?? ''}`,
          bold: true
        })],
        heading: HeadingLevel.HEADING_3,
        spacing: { before: 300, after: 100 },
      }),
      new Paragraph({
        children: [new TextRun({
          text: displayAnswer,
          color: isNotFound ? 'dc2626' : '111827'
        })],
        spacing: { after: 100 },
      })
    )

    if (!isNotFound && citations.length > 0) {
      children.push(new Paragraph({
        children: [
          new TextRun({ text: 'Sources: ', bold: true, size: 18, color: '4b5563' }),
          new TextRun({ text: citations.join(' · '), size: 18, color: '4b5563', italics: true }),
        ],
        spacing: { after: 50 },
      }))
    }

    if (!isNotFound && confidence > 0) {
      const pct = Math.round(confidence * 100)
      children.push(new Paragraph({
        children: [new TextRun({
          text: `Confidence: ${pct}%`,
          size: 18,
          color: pct >= 70 ? '16a34a' : pct >= 40 ? 'ca8a04' : 'dc2626'
        })],
        spacing: { after: 200 },
      }))
    }
  })

  const doc = new Document({ sections: [{ children }] })
  const buffer = await Packer.toBuffer(doc)
  const fileName = `${project?.name?.replace(/\s+/g, '-') ?? 'answers'}-${new Date().toISOString().split('T')[0]}.docx`

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${fileName}"`,
    },
  })
}